@echo off
echo Starting FileSharer Rebuild...

echo Starting Backend (Java)...
start "FileSharer Backend" cmd /k "cd backend && java -jar target/filesharer-backend-1.0-SNAPSHOT.jar"

echo Starting Frontend (Next.js)...
cd ui
echo Installing dependencies (if needed)...
call npm install
echo Starting Next.js Dev Server...
npm run dev
